### ISSUE TITLE
bundle install --deployment requires Gemfile.lock

### ISSUE THREAD

**Issue by pniederlag** [TYPO3-cookbooks/redmine#2]
vagrant@redmine-berkshelf:/srv/redmine/releases/c4164a0a7f795a313fa6d400db18ecf709e2d31f$ bundle  install --binstubs --deployment --without development test

The --deployment flag requires a Gemfile.lock. Please make sure you have checked your Gemfile.lock into version control before deploying.

**Comment by stucki** [comment]
Yeah that's true. You will therefore need to create a version in your Redmine Git repository which contains the file. To build the file once, run bundle with the --no-deployment flag.

**Comment by pniederlag** [comment]
I know, its even documented in the README, but I'd still consider this is a bug in the cookbook. In general the cookbook should just work on any fresh machine.

Just hang on... I am making good progress!

**Comment by StephenKing** [comment]
Hi,

I think we talked about that some time ago.. if one wants to have a reproducible deployment, a `Gemfile.lock` should be added to the repo. Best would be, of course, if the cookbook respects its existence/absence and then uses the correct bundler parameters.

Nice to hear that you're making progress :-)

**Comment by pniederlag** [comment]
redmine in its Gemfile includes Gemfile.local (custom layer) plus any Gemfile by a plugin plus it considers for example the type of database in config/database.yml. To put it short: redmine Gemfile has super cow power which is cut as soon as a Gemfile.lock is "in the way"...

I think it needs some attribute(?) in the cookbook that either says "deployment mode", which then requires a Gemfile.lock, or says "development mode", which just resolves the dependencies as they are required.

Or is it just sufficient to check wether Gemfile.lock is present or not?

**Comment by stucki** [comment]
I think an attribute would make most sense for this. It could be turned on and off on purpuse, rathern than using --no-deployment automagically...

**Comment by stucki** [comment]
We're still not using `Gemfile.lock` but have omitted the `--deployment` flag, which seems to do the job.
